<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.2" name="tileset" tilewidth="16" tileheight="16" spacing="1" tilecount="132" columns="12">
 <image source="../Tilemap/tilemap.png" width="203" height="186"/>
 <tile id="0" class="wall"/>
 <tile id="1" class="wall"/>
 <tile id="2" class="wall"/>
 <tile id="3" class="wall"/>
 <tile id="4" class="wall"/>
 <tile id="5" class="wall"/>
 <tile id="6" class="wall"/>
 <tile id="7" class="wall"/>
 <tile id="8" class="wall"/>
 <tile id="9" class="wall"/>
 <tile id="10" class="wall"/>
 <tile id="11" class="wall"/>
 <tile id="12" class="wall"/>
 <tile id="13" class="wall"/>
 <tile id="14" class="wall"/>
 <tile id="15" class="wall"/>
 <tile id="16" class="wall"/>
 <tile id="17" class="wall"/>
 <tile id="18" class="wall"/>
 <tile id="19" class="wall"/>
 <tile id="20" class="wall"/>
 <tile id="21" class="wall"/>
 <tile id="22" class="wall"/>
 <tile id="23" class="wall"/>
 <tile id="24" class="wall"/>
 <tile id="25" class="wall"/>
 <tile id="26" class="wall"/>
 <tile id="27" class="wall"/>
 <tile id="28" class="wall"/>
 <tile id="29" class="wall"/>
 <tile id="31" class="wall"/>
 <tile id="32" class="wall"/>
 <tile id="33" class="wall"/>
 <tile id="34" class="wall"/>
 <tile id="35" class="wall"/>
 <tile id="40" class="wall"/>
 <tile id="41" class="wall"/>
 <tile id="43" class="wall"/>
 <tile id="44" class="wall"/>
 <tile id="45" class="wall"/>
 <tile id="46" class="wall"/>
 <tile id="47" class="wall"/>
 <tile id="57" class="wall"/>
 <tile id="58" class="wall"/>
 <tile id="59" class="wall"/>
 <tile id="60" class="playerSpawner"/>
 <tile id="61" class="enemySpawner"/>
</tileset>
